# Generated by Django 4.0.3 on 2022-07-24 12:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_post_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 24, 12, 36, 15, 460518, tzinfo=utc)),
        ),
    ]
