# Generated by Django 4.0.3 on 2022-07-26 12:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='profile_info',
            new_name='Profile',
        ),
    ]
